Repository brainer3220/ITmmunity, pull requests merged in 2021-12, with the labels that each got.

#106 Change to Jetpack Compose design pattern
  app/src/main/java/com/brainer/itmmunity/MainActivity.kt
Labels: Medium

#109 Delete first 3 contents for meeco
  app/src/main/java/com/brainer/itmmunity/MainActivity.kt
Labels: Extra Small

#111 Fixed changing of Appbar color in light theme
  app/build.gradle
  app/src/main/java/com/brainer/itmmunity/ui/theme/Theme.kt
Labels: Extra Small

#114 Updated Theme.kt file
  app/src/main/java/com/brainer/itmmunity/ui/theme/Theme.kt
Labels: No Changes

#115 updated build gradle file
  app/build.gradle
Labels: Extra Small
